defmodule Discuss.Router do
  use Discuss.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discuss.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Discuss do # scope: namespaces urls
    pipe_through :browser # Use the default browser stack

    get "/", TopicController, :index
    # get "/topics", TopicController, :index
    # get "/topics/new", TopicController, :new
    # post "/topics", TopicController, :create
    # get "/topics/:id/edit", TopicController, :edit
    # put "/topics/:id", TopicController, :update
    # delete "/topics/:id", TopicController, :delete
    resources "/topics", TopicController # creates routes commented above: REST conventions
  end

  scope "/auth", Discuss do
    pipe_through :browser

    # usually signout should be a POST or DEL but oh well...
    get "/signout", AuthController, :sign_out

    # request function generated by the ueberauth module
    # provider is interpreted by the ueberauth to choose the correct strategy (in our case provider == github)
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Discuss do
  #   pipe_through :api
  # end
end
